# Generated by Django 5.0.1 on 2025-11-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('favorite_sport', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], max_length=20)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'player_profiles',
            },
        ),
    ]
